### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Gregorcnik** [Gregorcnik/Beeptest#1]
Naredi:
- [x] popravi navodila
- [x] gumb ustavi
- [ ] napisi 12/3 in bo sam zgeneriral pesem
- [ ] dodaj UI za ritem
- [x] dodaj nekaj stila
